stop() takes 1 positional argument but 3 were given
(<class 'TypeError'>, TypeError('stop() takes 1 positional argument but 3 were given'), <traceback object at 0x731cdcd01040>)
Traceback (most recent call last):
  File "/tmp/ipykernel_22716/705264848.py", line 63, in <module>
    predictions = model.predict(image, verbose=0)
  File "/home/rutalab/mambaforge/envs/flyprojection/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/rutalab/mambaforge/envs/flyprojection/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 1189, in _numpy
    return self._numpy_internal()
TypeError: stop() takes 1 positional argument but 3 were given
